version: "3.0"
services:
  elasticsearch7:
    container_name: elastic-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - docker_data:/usr/share/elasticsearch/data
    networks:
      - elastic-net
    ports:
      - 9200:9200
  # kibana:
  #   container_name: kb-container
  #   image: docker.elastic.co/kibana/kibana:7.11.0
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://es-container:9200
  #   networks:
  #     - elastic-net
  #   depends_on:
  #     - elasticsearch
  #   ports:
  #     - 5601:5601
volumes:
  docker_data:
    driver: local
networks:
  elastic-net:
    driver: bridge